// Generated by @lynx-js/autolink-codegen. Do not edit.
#ifndef EXPLORER_SHOWCASE_NATIVE_OPENCV_DOCUMENT_SCANNER_IOS_ADDON_USE_H_
#define EXPLORER_SHOWCASE_NATIVE_OPENCV_DOCUMENT_SCANNER_IOS_ADDON_USE_H_

#if __has_include(<LynxWeakNodeAPI/headers/node_api.h>)
#include <LynxWeakNodeAPI/headers/node_api.h>
#else
#include "node_api.h"
#endif

#if defined(USE_WEAK_SUFFIX_NAPI)
#if __has_include(<LynxWeakNodeAPI/headers/weak_napi_defines.h>)
#include <LynxWeakNodeAPI/headers/weak_napi_defines.h>
#else
#include "weak_napi_defines.h"
#endif
#endif

#ifndef NAPI_USE
#define NAPI_USE(modname)                                         \
  EXTERN_C_START                                                  \
  extern void _napi_register_xx_##modname(void);                  \
  __attribute__((used)) static void* _napi_module_##modname##_p = \
      (void*)&_napi_register_xx_##modname;                        \
  EXTERN_C_END
#endif

NAPI_USE(OpenCVDocumentScanner)

#if defined(USE_WEAK_SUFFIX_NAPI)
#if __has_include(<LynxWeakNodeAPI/headers/weak_napi_undefs.h>)
#include <LynxWeakNodeAPI/headers/weak_napi_undefs.h>
#else
#include "weak_napi_undefs.h"
#endif
#endif

#endif  // EXPLORER_SHOWCASE_NATIVE_OPENCV_DOCUMENT_SCANNER_IOS_ADDON_USE_H_
