// Generated by @lynx-js/autolink-codegen. Do not edit.
extern "C" void _napi_register_xx_OpenCVDocumentScanner(void);

extern "C" void LynxAutolinkRegisterNapiNativeModules() {
  _napi_register_xx_OpenCVDocumentScanner();
}
