// Generated by @lynx-js/autolink-codegen. Do not edit.
using NodeEnv = void*;
using NodeValue = void*;
using LynxLibraryNapiModuleCreator = NodeValue (*)(NodeEnv env,
                                                   NodeValue exports,
                                                   const char* module_name,
                                                   void* opaque);

extern "C" NodeValue LynxAutolinkCreateOpenCVDocumentScanner(
    NodeEnv env, NodeValue exports, const char* module_name, void* opaque);

extern "C" void lynx_env_register_native_module(
    const char* name, LynxLibraryNapiModuleCreator creator, void* opaque);

extern "C" void LynxAutolinkRegisterNapiNativeModules() {
  lynx_env_register_native_module("OpenCVDocumentScanner",
                                  LynxAutolinkCreateOpenCVDocumentScanner,
                                  nullptr);
}
